language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - .autoconf
  - $HOME/.m2
before_install:
  - mvn install:install-file -DgroupId=org.xerial -DartifactId=sqlite-jdbc -Dversion=3.7.8 -Dfile=lib/sqlite-jdbc-3.7.8.jar -Dpackaging=jar -DgeneratePom=true
