language: java
jdk:
  - oraclejdk8
env:
  - SCHEMACRAWLER_VERSION=15.03.04
cache:
  directories:
  - .autoconf
  - $HOME/.m2
before_deploy:
  - export RELEASE_PKG_FILE=$(ls target/*.deb)
  - echo "deploying $RELEASE_PKG_FILE to GitHub releases"
  - git fetch --tags
deploy:
  provider: releases
  api_key:
    secure: Vwl5dp9As8OjcO6vcMivSqc92JGpsWJcX1xGhFhpjk4Jo0wBaFEs+SgfxqU59lPiF6r7uoBTpHUcnuYqEWtWMq7r63RMxEGXnbJgsKk5yorkBqroQDABl/L/WW6LOudXzTY8yDWou8Bcw0YUZy2rl1+2IlVoCmmfNkoGlaE3wyY=
  file: target/*.deb
  file_glob: true
  file: "${RELEASE_PKG_FILE}"
  skip_cleanup: true
  on:
    tags: true
    repo: adriens/schemacrawler-deb
    all_branches: true
