language: java
jdk:
  - oraclejdk8
env:
  - SCHEMACRAWLER_VERSION=12.06.03
cache:
  directories:
  - .autoconf
  - $HOME/.m2
before_install:
  - mvn install:install-file -DgroupId=org.xerial -DartifactId=sqlite-jdbc -Dversion=3.7.8 -Dfile=lib/sqlite-jdbc-3.7.8.jar -Dpackaging=jar -DgeneratePom=true
after_success:
  - sudo dpkg -i target/schemacrawler-deb_${SCHEMACRAWLER_VERSION}_all.deb
